spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: admin
      url: jdbc:mysql://localhost/sell?characterEncoding=utf-8&useSSL=false
    jpa:
      show-sql: true
server:
  servlet:
    context-path: /sell